apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: test-1
  annotations:
    notifications.argoproj.io/subscribe.on-sync-synced.github: ""
spec:
  git:
    repo: https://github.com/nan-yu/deployment-2
    branch: main
    auth: none
  notificationConfig:
    secretRef:
      name: notification-secret
    configmapRef:
      name: notification-cm-root-sync
