apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-synced.github: ""
  name: root-sync-2
  namespace: config-management-system
spec:
  git:
    auth: none
    branch: main
    repo: https://github.com/nan-yu/deployment-2
  sourceFormat: unstructured
  sourceType: git
  notificationConfig:
    secretRef:
      name: notification-secret
    configmapRef:
      name: notification-cm-root-sync
